### ISSUE TITLE
License type?

### ISSUE THREAD

**Issue by mellegge** [darkplusplus/cot#3]
What is the license for COT library?

Thanks

**Comment by gregbuehler** [comment]
Let's make this easy and just use the MIT license. 

The file https://github.com/darkplusplus/cot/blob/main/dpp.cot/CoTtypes.xml is copyright Mitre, but I believe it's provenience was http://cot.mitre.org/ which is no longer accessible. A copy can be found within https://github.com/Esri/solutions-geoevent-java which is Apache 2.0 if we _really_ need to maintain license lineage.
